name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install bazel via bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    # Disabled until there is actually something to test here
    # - name: Test root
    #   run: |
    #     "${GITHUB_WORKSPACE}/bin/bazel" test //...

    - name: Test test Terraform
      run: |
        cd test && "${GITHUB_WORKSPACE}/bin/bazel" test --test_output=errors //...
